### ISSUE TITLE
Admin UI demo: FormClasses => DropDownSelect throws error and fails

### ISSUE THREAD

**Issue by kylenstone** [fuzz-productions/Mortar-JS#1]
```
Warning: MediumEditor: prop type `onChange` is invalid; it must be a function, usually from React.PropTypes.
Uncaught ReferenceError: classes is not defined
```

Errors are thrown and UI does not update as expected.
![screen shot 2016-02-05 at 11 23 05 am](https://cloud.githubusercontent.com/assets/893851/12852012/eb35adba-cbfa-11e5-952d-fea275082f3f.png)

**Comment by Pink401k** [comment]
Thanks for the report.  I have a fix incoming.  Hopefully will be pushing it up end of day today.

**Comment by Kyle-Mendes** [comment]
This has been resolved, and the changes are live on the [playground](http://playground.mortarjs.io).
