### ISSUE TITLE
Remove all "require('assign');"

### ISSUE THREAD

**Issue by Kyle-Mendes** [fuzz-productions/Mortar-JS#13]
I think we can remove all instances of `require('assign');`

[Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) exists on the Object prototype, and I don't think using the Facebook version affords us anything extra.

**Comment by walterbm** [comment]
From my research it seems that React's version of `assign` was only meant as a poly fill until the ES6 version of `Object.assign()` matured. The official React documentations now [points to the ES6 implementation](https://facebook.github.io/react/docs/transferring-props.html) so the two versions are most likely identical in functionality.

**Comment by walterbm** [comment]
Done. See PR #17

**Comment by Kyle-Mendes** [comment]
@walterbm Was this also done in the generator?
