### ISSUE TITLE
Investigate removing and replacing dependencies 

### ISSUE THREAD

**Issue by walterbm** [fuzz-productions/Mortar-JS#20]
- [ ] `classnames` (Kyle & Walter)
- [ ] `reqwest` (Walter)
- [ ] `fuse` (Kyle)
- [ ] `validator` (Kyle)

These are very important dependencies for Mortar but it may be possible to replace the functionality with our own implementations. This may be easier for `classnames` and `reqwest` than the others

- [ ] React Router

This will be a bigger investment and should be evaluated critically before actions are taken.  However, rolling our own `Router` component has definite benefits that should be considered.

**Comment by Kyle-Mendes** [comment]
@walterbm What do you think should be done with this issue?  It hasn't had any progress in a while.  Should we move it to the back burner?

**Comment by walterbm** [comment]
@Kyle-Mendes moving these to the back-burner seems fine with me. 

Only `react router` and the validator (our fork of `js-schema`) need to be replaced since we are now irrevocably behind the upgrade path for those two dependencies. But right now neither is causing any significant issues so we can focus on other Mortar features before revisiting.

**Comment by Kyle-Mendes** [comment]
react-router isn't behind. We're on one of the most up-to-date releases that they have :).

But I'll look into validator. I'm not really even sure if we're using that.
