### ISSUE TITLE
Upgrade to React 15

### ISSUE THREAD

**Issue by walterbm** [fuzz-productions/Mortar-JS#25]
React 15 has been officially released. Most of the breaking changes do not affect any Mortar components. However we rely on `react-router 1.0.1` (specifically the named-routes functionality). In order to complete the upgrade react-router or create our own lightweight router.

**Comment by SimantovYousoufov** [comment]
Passing in single JSX elements into Form and Row like:

```
<Br.Form key={this.formKey} formKey={this.formKey} bindResource={this.state.includeRelations}>
    <Br.Row>
	<Br.Column grid="lg" size="12">
	    {this.buildRelationsCheckboxes(relations)}
        </Br.Column>
    </Br.Row>
</Br.Form>
```

Produces these errors:
`warning.js?8a56:44 Warning: Failed propType: Invalid prop children of type object supplied FormRow, expected array. Check the render method of YourComponent`
`warning.js?8a56:44 Warning: Failed propType: Invalid prop children of type object supplied to Form, expected array. Check the render method of YourComponent`

Form and Row should accept the `React.PropTypes.object` type for `children`

**Comment by Kyle-Mendes** [comment]
@SimantovYousoufov This is related to #14

**Comment by Kyle-Mendes** [comment]
We are now fully supporting React 15.

React Router was also upgraded in the Playground.
