### ISSUE TITLE
Docs: Odd behavior with search filter

### ISSUE THREAD

**Issue by MTen** [fuzz-productions/Mortar-JS#29]
Improvement 1: searching for stuff that has no results displays nothing. (trivial)

Bug 1: Search Filter has words that seem "actionable" which are provided by the client browser like pattern, authentication-helper.js, support, & _support. (minor, confusing to user)

Bug 2: type in individual letters form a - Z until predictive results come up. Once a predictive result comes up, hit enter, predictive search still overlays the search results. (minor, gui annoyance)

https://www.youtube.com/watch?v=EATu0Q5zqKQ

**Comment by Kyle-Mendes** [comment]
This is an issue with `jsdoc` which we use to auto-generate the documentation site.  We could look into fixing by diving into the generated code.  However, that's a lower priority for right now, so I'm going to close at `wontfix` for now. 

Thank you for the report though!
