### ISSUE TITLE
Docs: Typos in Documentation. Minor

### ISSUE THREAD

**Issue by MTen** [fuzz-productions/Mortar-JS#30]
The end of "Manual installation" body is cut off.
The end of "Contributing" is cut off.

![mortar - docs - typos](https://cloud.githubusercontent.com/assets/5403486/15198664/c26b8416-17a6-11e6-8e78-2e54dcd08707.png)

**Comment by Kyle-Mendes** [comment]
Good catch. This has been fixed and will be included in the upcoming release!
